[mongo]
#host = "ec2-13-60-8-103.eu-north-1.compute.amazonaws.com"
#port = 27017
#username = "admin"
#password = "password"
#database = "Results"
url = "mongodb://admin:IHEPOKZADN%3FSQDNSQSLQJDOAZEZAOENCWBC%3FWBCKJDSOZADQSD%5F1342323%5FDHKJDSD@ec2-13-51-204-81.eu-north-1.compute.amazonaws.com:27017/Results?authSource=Results"
